name: Send a tweet
on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Text of tweet, up to 240 Chars'
        required: true
        default: 'Hi this is a tweet'

jobs:
  send_tweet:
    name: send tweet job
    runs-on: ubuntu-latest
    steps:
      - uses: ethomson/send-tweet-action@v1
        with:
          status: '${{ github.event.inputs.message }}'
          consumer-key: ${{ secrets.TWITTER_MODERNAPPSBYTANZU_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_MODERNAPPSBYTANZU_API_SECRET_KEY }}
          access-token: ${{ secrets.TWITTER_MODERNAPPSBYTANZU_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_MODERNAPPSBYTANZU_ACCESS_TOKEN_SECRET}}  